//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinDatXe
    {
        public int MaDatXe { get; set; }
        public string SoDienThoai { get; set; }
        public string DiemDon { get; set; }
        public string DiemDen { get; set; }
        public string SoKm { get; set; }
        public string ThoiGian { get; set; }
        public string ThanhTien { get; set; }
        public string LoaiXe { get; set; }
        public string ThanhToan { get; set; }
        public string NgayGioDat { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
