//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaUngDung
    {
        public int MaDanhGia { get; set; }
        public string SoDienThoai { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
        public Nullable<int> MucDo { get; set; }
        public string NoiDung { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiXe TaiXe { get; set; }
    }
}
