//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaTaiXe
    {
        public int MaDanhGiaTX { get; set; }
        public string KHDanhGia { get; set; }
        public string TKTaiXe { get; set; }
        public int MucDo { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiXe TaiXe { get; set; }
    }
}
