//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanTin
    {
        public int MaNhanTin { get; set; }
        public string SDTNguoiNhan { get; set; }
        public string SDTNguoiGui { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> TrangThaiXem { get; set; }
        public string CamXuc { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
