//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanNganHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoanNganHang()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int MaTaiKhoanNH { get; set; }
        public string SoDienThoai { get; set; }
        public string CCCD { get; set; }
        public string MatTruocCCCD { get; set; }
        public string MatSauCCCD { get; set; }
        public string SoThe { get; set; }
        public int SoTaiKhoan { get; set; }
        public string ChuThe { get; set; }
        public int ThoiHanThang { get; set; }
        public int ThoiHanNam { get; set; }
        public int CVV { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
