//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiXe()
        {
            this.DanhGiaTaiXes = new HashSet<DanhGiaTaiXe>();
            this.TaiXeNhanChuyenXes = new HashSet<TaiXeNhanChuyenXe>();
        }
    
        public int MaTX { get; set; }
        public string SoDienThoai { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgayThangNamSinh { get; set; }
        public string Email { get; set; }
        public string BienSo { get; set; }
        public string CCCD { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> MucDoDanhGiaTB { get; set; }
        public Nullable<decimal> DiemUyTin { get; set; }
        public string ViTri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaTaiXe> DanhGiaTaiXes { get; set; }
        public virtual DanhGiaUngDung DanhGiaUngDung { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiXeNhanChuyenXe> TaiXeNhanChuyenXes { get; set; }
    }
}
