//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int MaThanhToan { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<int> MaTaiKhoanNH { get; set; }
        public Nullable<int> MaDatXe { get; set; }
        public Nullable<int> MaKhuyenMai { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string HinhThucThanhToan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual TaiKhoanNganHang TaiKhoanNganHang { get; set; }
        public virtual ThongTinDatXe ThongTinDatXe { get; set; }
    }
}
