//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinDatXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinDatXe()
        {
            this.TaiXeNhanChuyenXes = new HashSet<TaiXeNhanChuyenXe>();
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int MaDatXe { get; set; }
        public string SoDienThoai { get; set; }
        public string DiemDon { get; set; }
        public string DiemDen { get; set; }
        public string SoKm { get; set; }
        public string ThoiGian { get; set; }
        public string ThanhTien { get; set; }
        public string LoaiXe { get; set; }
        public string HinhThucThanhToan { get; set; }
        public System.DateTime NgayGioDat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiXeNhanChuyenXe> TaiXeNhanChuyenXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
